server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: authlog
  static_configs:
  - targets:
      - authlog
    labels:
      job: authlog
      __path__: /logs/auth.log

- job_name: syslog
  static_configs:
  - targets:
      - syslog
    labels:
      job: syslog
      __path__: /logs/syslog

- job_name: docker_logs
  static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        container_name: "{{.ContainerName}}" # Add container name dynamically
        __path__: /var/lib/docker/containers/*/*.log      