global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000']
    # metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']   
         
  # - job_name: 'frontend'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['frontend:5173']
  #   metrics_path: '/tam-metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
